cloudformation:Add support arm based machines
scylladb/scylla-machine-image pull request #305
Opened 2022-02-20 10:16 UTC by yaronkaikov

This is a preperation for https://github.com/scylladb/scylla-pkg/issues/2616. In order to support AMI promote for arm based arch, we need to generate the cloudformation yaml file based on the relevant instance types

Adding a condition based on parameter that we will pass during the template generating process
    
Thanks to @benipeled for the providing the quick solution

2022-02-20 10:35 UTC, fruch commented
Should you also revert #302  in this one ?

2022-02-20 10:43 UTC, yaronkaikov commented
@fruch Since it's not in master (next-machine-image is broken)  i reverted this commit

2022-02-20 10:44 UTC, yaronkaikov commented
In any case. don't merge, since i will verify it with jenkins job (locally it's working)

2022-02-20 21:01 UTC, yaronkaikov commented
Verification:
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/ami/1251/

@fruch Can you please approve and merge

2022-02-21 06:52 UTC, benipeled requested changes

2022-02-21 06:52 UTC, benipeled commented on aws/cloudformation/scylla.yaml.j2
> +{% if 'aarch64' in arch %}
You can short it with `{% elif 'aarch64' in arch %}`

2022-02-21 07:07 UTC, benipeled approved these changes

2022-02-21 10:04 UTC, merged

2022-02-21 10:06 UTC, bentsi approved these changes