Drop CentOS based machine-image
scylladb/scylla-machine-image pull request #368
Opened 2022-06-20 00:54 UTC by syuu1228

Since we moved to Ubuntu based machine-image, we nolonger need older
CentOS based machine-image.
Let's drop CentOS related code, and simlify build scripts.

This includes following changes:
 - Drop scylla-machine-image .rpm
 - Drop CentOS related code from scylla_image_setup and scylla_cloud.py
 - Drop build_image.sh and build_with_docker.sh
 - Drop CentOS related code from scylla_install_image
 - Optimize scylla_install_image to python3 (it supports both 2 and 3 now)
 - Drop CentOS related code form scylla.json
 - move https://github.com/scylladb/scylla-machine-image/commit/9e42255ca1d5faff8f531ccc75b6c2c9ed645b5d to scylla_install_image to reduce scylla-image-setup.service boot up time

2022-06-20 12:50 UTC, yaronkaikov requested changes

2022-06-20 12:50 UTC, yaronkaikov commented on common/scylla_image_setup
> +from lib.scylla_cloud import get_cloud_instance, is_gce
I think we should still have the ability to install machine image on rpm based OS and run `scylla_io_setup` for example. we recently had a customer that worked on `Rhel8` and installed it manually 

Let's drop only the code related directly to building image based on rpm

2022-07-05 14:57 UTC, syuu1228 commented
@yaronkaikov ping

2022-07-06 04:42 UTC, yaronkaikov commented
Verification passed: https://jenkins.scylladb.com/view/master/job/scylla-master/job/releng-testing/job/ami/1377/

2022-07-06 04:43 UTC, yaronkaikov approved these changes
LGTM

2022-07-06 04:43 UTC, merged