SCYLLA-VERSION-GEN: use semver-compatible version
scylladb/scylla-machine-image pull request #371
Opened 2022-07-04 09:02 UTC by yaronkaikov

Scylla-operator require Scylla to have semantic versioning. (Ref: https://semver.org/)
release candidate versioning already being updated in machine-image (https://github.com/scylladb/scylla-machine-image/pull/359/commits/e36e5a7260684f72f845e148d0822569631f27bd)

Nightly builds should be also aligned with this change

Ref: https://github.com/scylladb/scylla/issues/9543

2022-07-04 09:06 UTC, fruch submitted a review, later dismissed
LGTM

2022-07-04 09:28 UTC, vponomaryov requested changes

2022-07-04 09:32 UTC, yaronkaikov commented on SCYLLA-VERSION-GEN
> +VERSION=5.1.0~dev
with (`-`) is not working (ref: https://github.com/semver/semver/issues/145) 

according to https://jubianchi.github.io/semver-check `5.1.0~dev` is valid

2022-07-04 09:34 UTC, vponomaryov commented on SCYLLA-VERSION-GEN
> +VERSION=5.1.0~dev
> according to https://jubianchi.github.io/semver-check `5.1.0~dev` is valid

No, it is not. Exactly hyphen is proper symbol.

2022-07-07 14:04 UTC, vponomaryov submitted a review, later dismissed
LGTM

2022-07-25 10:47 UTC, benipeled approved these changes
LGTM

2022-07-25 11:01 UTC, merged