machine-image: change base image to Ubuntu 22.04
scylladb/scylla-machine-image pull request #404
Opened 2022-09-28 09:28 UTC by benipeled

This commit bumps the image base-version to Ubuntu 22.04

**Note:** this change is currently blocked by cloudformation issue [0], if it will not going to fix soon, we'll need to use a workaround to adjust the python modules paths as suggested on [0]

[0] https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1304

Fix #390

2022-09-28 19:12 UTC, yaronkaikov commented
@benipeled The changes it self looks good, but we need the cloudformation working as well. so let's fix it here (another commit) and merge it together

2022-09-29 06:24 UTC, benipeled commented
@yaronkaikov we're not going to fix it on our side but waiting for the fix on [0],
we have no rush with this change but if it will not fix before 5.2, we'll add a WA, for now let's leave it as draft

2022-09-29 06:37 UTC, fruch commented
@benipeled even that SCT should be ready for 22.04, did you run any job with those images ? at least artifacts_ami ?

2022-09-29 06:51 UTC, benipeled commented
@fruch yes and it failed https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/next-machine-image/475/
we'll need to re-run verification once the cfn will be fixed but you're right, we can start adjusting the SCT

2022-09-29 07:04 UTC, fruch commented
> @fruch yes and it failed https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/next-machine-image/475/ we'll need to re-run verification once the cfn will be fixed but you're right, we can start adjusting the SCT

it failed cause of spot termination, both gce and azure passed cleanly.

2022-09-29 12:56 UTC, benipeled commented
@fruch https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/next-machine-image/477/ passed successfully,
let me know if there are any other requirements from SCT side for this change,

In any case, I'll rerun verification once we'll have the cfn fix

2022-11-08 15:28 UTC, benipeled commented
We're no longer blocked by the cloudformation helper-scripts,
I verified this change with [1] - ubuntu 22.04.1 LTS & scylla 5.2.0~dev-0.20221107.a9063f9582f0 - it works as expected,

The target release for this change is 5.2, no early versions will release with ubuntu 22.04

@roydahan @fruch are there any other tests you want to run before merging this change?

PS> This PR should be merged together with https://github.com/scylladb/scylla-pkg/pull/3149

[1] https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/next-machine-image/518/

2022-11-08 15:42 UTC, roydahan commented
If you can trigger AMI-test in releng-testing that triggers even one longevity job it will be great.

2022-11-08 16:55 UTC, benipeled commented
> If you can trigger AMI-test in releng-testing that triggers even one longevity job it will be great.

AMI built successfully - https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/ami/1757/
artifacts-ami-test finished successfully -https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/artifacts/job/artifacts-ami-test/160/

A few longevity jobs are running...

2022-11-09 08:46 UTC, yaronkaikov requested changes

2022-11-09 08:51 UTC, fruch commented on packer/build_image.sh
> +    echo "  [--operating-system]    Set the base OS for the image. default is $OPERATING_SYSTEM"
not clear why it was introduced in:
https://github.com/scylladb/scylla-machine-image/commit/4e1144a677bc5b0e171b37ec254ec31710a3c278

2022-11-09 08:52 UTC, fruch commented on packer/build_image.sh
> +    echo "  [--operating-system]    Set the base OS for the image. default is $OPERATING_SYSTEM"
I agree that no part of the code uses it

2022-11-09 13:08 UTC, benipeled commented
@roydahan @fruch longevity results

https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/longevity/job/longevity-100gb-4h-test/26/ - SUCCESS
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/longevity/job/longevity-10gb-3h-scylla-debug-test/25/ - FAILED on `test_custom_time` - timeout?

```
14:34:08  ======================================================================
14:34:08  ERROR: test_custom_time (longevity_test.LongevityTest)
14:34:08  Run cassandra-stress with params defined in data_dir/scylla.yaml
14:34:08  ----------------------------------------------------------------------
14:34:08  sdcm.sct_events.system.TestResultEvent: ================================= TEST RESULTS =================================
14:34:08  
14:34:08  ----- LAST ERROR EVENT -------------------------------------------------------
14:34:08  2022-11-09 12:23:12.033: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=552b4f43-a267-40a1-9a4f-eb6f3e0520e1, source=LongevityTest.test_custom_time (longevity_test.LongevityTest)() message=Traceback (most recent call last):
14:34:08  File "/home/ubuntu/scylla-cluster-tests/longevity_test.py", line 140, in test_custom_time
14:34:08  self.verify_stress_thread(cs_thread_pool=stress)
14:34:08  File "/home/ubuntu/scylla-cluster-tests/sdcm/tester.py", line 1922, in verify_stress_thread
14:34:08  results, errors = cs_thread_pool.verify_results()
14:34:08  File "/home/ubuntu/scylla-cluster-tests/sdcm/stress_thread.py", line 285, in verify_results
14:34:08  for future in concurrent.futures.as_completed(self.results_futures, timeout=self.timeout):
14:34:08  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 241, in as_completed
14:34:08  raise TimeoutError(
14:34:08  concurrent.futures._base.TimeoutError: 1 (of 2) futures unfinished
```

2022-11-09 13:17 UTC, fruch commented
@benipeled the debug job is disabled on master, so one is tracking its results.

So it's kind of pointless to keep triggering it.

It's basically says the Cassandra stress didn't finish in time we expected. which might be o.k. since it's using a debug build. But again we don't have enough information for this job history.

2022-11-09 13:17 UTC, fruch commented
It's green light from my POV to do the switch.

2022-11-10 04:14 UTC, syuu1228 approved these changes
LGTM

2022-11-10 11:46 UTC, yaronkaikov approved these changes
LGTM

2022-11-10 12:23 UTC, merged