gce: enable multi-queue SCSI
scylladb/scylla-machine-image pull request #419
Opened 2022-12-09 16:47 UTC by syuu1228

To getting better performance on GCP instances with SCSI local disks, google cloud document recommends to enable VIRTIO_SCSI_MULTIQUEUE flag on guestOsFeatures and following kernel parameter "scsi_mod.use_blk_mq=Y".

Fixes #418

2022-12-10 19:58 UTC, yaronkaikov commented
Verified with https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/next-machine-image/538

2022-12-10 19:58 UTC, yaronkaikov approved these changes
@syuu1228 Please verify that the module is actually loaded when creating an instance based on a fixed image. 
according to https://cloud.google.com/compute/docs/disks/optimizing-local-ssd-performance#multiqueue

we should be able to see an output of `Y` when running  `cat /sys/module/scsi_mod/parameters/use_blk_mq`

2022-12-10 20:08 UTC, yaronkaikov requested changes

2022-12-10 20:08 UTC, yaronkaikov commented on packer/scylla_install_image
> +        kernel_opt = ' scsi_mod.use_blk_mq=Y'
Based on the image created during the verification you did, i don't see this option available @syuu1228

2022-12-11 07:29 UTC, mykaul commented
Please check if we don't need to enable dm_mod.use_blk_mq=y if you are using device mapper multipath - and you may be (even on local disks)

2022-12-11 07:32 UTC, mykaul commented
> Please check if we don't need to enable dm_mod.use_blk_mq=y if you are using device mapper multipath - and you may be (even on local disks)

My laptop:
```
[ykaul@ykaul ~]$ sudo cat /sys/module/dm_mod/parameters/use_blk_mq
Y
```

2022-12-11 18:37 UTC, avikivity commented
> To getting better performance on GCP instances with SCSI local disks, google cloud document recommends to enable VIRTIO_SCSI_MULTIQUEUE flag on guestOsFeatures and following kernel parameter "scsi_mod.use_blk_mq=Y".
> 
> Fixes #418

Are those instances relevant? We should be using instances with nvme interfaces. Are some instance types not available with nvme?

Please check that the kernel option survives a kernel upgrade.

2022-12-11 18:40 UTC, avikivity commented
The option was removed in torvalds/linux@6a23e05c2fe3c64ec012fd81e51e3ab51e4f2f9f

2022-12-11 18:53 UTC, syuu1228 commented
> Please check if we don't need to enable dm_mod.use_blk_mq=y if you are using device mapper multipath - and you may be (even on local disks)

Same as SCSI, seems like it's enabled by default.
Also, we don't use device mapper on our image.

2022-12-12 08:52 UTC, syuu1228 commented
> Unlike the GCE document says, we cannot verify MQ is enabled by `cat /sys/module/scsi_mod/parameters/use_blk_mq`, since built-in module dees not apperer on /sys/module, and scsi module is built-in module on Ubuntu GCE kernel.

This description was probably wrong, since /sys/module/scsi_mod/parameters/ itself is exists and there are some other parameters available but use_blk_mq is not available.

Correct reason is, same as device-mapper as @avikivity commented at https://github.com/scylladb/scylla-machine-image/pull/419#issuecomment-1345627101, the option was removed: https://github.com/torvalds/linux/commit/f664a3cc17b7d0a2bc3b3ab96181e1029b0ec0e6
So, since linux 5.0, we always use multiqueue mode.

2022-12-12 08:52 UTC, syuu1228 commented
I think we should close this since we don't need patch.

2022-12-12 08:52 UTC, closed without merging