Disable C1 sleep state for all IaaS
scylladb/scylla-machine-image pull request #430
Opened 2023-01-24 17:43 UTC by syuu1228

Since we want maximum performance and low latency, we need to disable C1 sleep state on instances.

Fixes #425

2023-01-24 17:45 UTC, syuu1228 commented
Verified boot finely, but I'm not sure how to check `intel_idle.max_cstate=1` and `processor.max_cstate=1` are working.
AWS doc suggested to use`turbostat` to do that, but I coudn't able to run it in our image.

2023-02-14 08:26 UTC, yaronkaikov requested changes

2023-02-14 09:05 UTC, mykaul commented on packer/scylla_install_image
> +                  fr'{grub_variable}="\1 net.ifnames=0 clocksource=tsc tsc=reliable intel_idle.max_cstate=1 processor.max_cstate=1 {kernel_opt}"', grub,
From  https://cloud.google.com/compute/docs/cpu-platforms : 
```
Processor power management technologies: Intel processors support multiple technologies to optimize the power consumption. These technologies are divided into two categories, or states:
C-states are states when the CPU has reduced or turned off selected functions. C-state is only supported for C2 machine types.
P-states provide a way to scale the frequency and voltage at which the processor runs so as to reduce the power consumption of the CPU. For VMs other than C2, C-State and P-State are not supported currently, so idling virtual CPUs within the guest environment might not work as expected.
```

2023-02-14 09:09 UTC, yaronkaikov commented on packer/scylla_install_image
> +                  fr'{grub_variable}="\1 net.ifnames=0 clocksource=tsc tsc=reliable intel_idle.max_cstate=1 processor.max_cstate=1 {kernel_opt}"', grub,
Also found https://learn.microsoft.com/en-us/previous-versions/windows/desktop/xperf/p-states-and-c-states . so i guess we can include it for all cloud images

2023-02-15 08:39 UTC, syuu1228 commented on packer/scylla_install_image
> +                  fr'{grub_variable}="\1 net.ifnames=0 clocksource=tsc tsc=reliable intel_idle.max_cstate=1 processor.max_cstate=1 {kernel_opt}"', grub,
I found that C-states control does not available on all instance types, it's only available on few instance type.
When it's not available, the kernel parameter (intel_idle.max_cstate=1 processor.max_cstate=1)  is just ignored.
And the parameter is not AWS specific thing, it is Intel/AMD CPU specific feature (and probably not all hypervisor expose it to the Guest VM, that's why supported instance is limited).
So I think it's safe to add on all images by default.

2023-02-19 05:57 UTC, yaronkaikov commented
Verified with https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/next-machine-image/54/

2023-02-19 05:58 UTC, yaronkaikov submitted a review, later dismissed

2023-02-19 06:03 UTC, yaronkaikov approved these changes

2023-02-19 06:12 UTC, merged