fix(scylla_create_devices): improve logic for found devices
scylladb/scylla-machine-image pull request #98
Opened 2021-02-18 07:19 UTC by aleksbykov

scylla_create_devices support 3 variants for data_device:
- auto: for aws instance will search nvme(ephemeral) device,
          if not found will search ebs volumes(ebs).
        for gce instances will search nvme(attached) devices
for aws instances:
- attached: will search ebs volumes(attached) and if such volumes
            added to os as nvme devices, will use them
- instance_store: will search nvme(ephemeral) devices and use

2021-02-22 10:56 UTC, bentsi commented on common/scylla_configure.py
> +            subprocess.run("/opt/scylladb/scylla-machine-image/scylla_create_devices --data-device {}".format(device_type), shell=True, check=True)
Use f-string:
```suggestion
            subprocess.run(f"/opt/scylladb/scylla-machine-image/scylla_create_devices --data-device {device_type}", shell=True, check=True)
```

2021-02-22 11:03 UTC, bentsi commented on common/scylla_create_devices
> +            raise Exception(f"No devices attached or instance_store were found devicetype")
```suggestion
            raise Exception(f"No block devices were found for '{device_type}' device type")
```

2021-02-22 11:06 UTC, bentsi requested changes
1) please address comments
2) did you check that `instance.ebs_disks()` and `instance.ephemeral_disks()` returns correct values?

2021-02-23 06:21 UTC, aleksbykov commented on common/scylla_create_devices
> +            raise Exception(f"No devices attached or instance_store were found devicetype")
Done

2021-02-23 06:21 UTC, aleksbykov commented on common/scylla_configure.py
> +            subprocess.run("/opt/scylladb/scylla-machine-image/scylla_create_devices --data-device {}".format(device_type), shell=True, check=True)
Done

2021-02-23 06:23 UTC, aleksbykov commented
> 1. please address comments

Done.
> 2. did you check that `instance.ebs_disks()` and `instance.ephemeral_disks()` returns correct values?

Yes, i had several instances with different configurations (ebs only as nvme, ebs only as attached, nvme+ebs) and i uploaded these files and check that disks correctly found and used. 
Also, i want to create new custom ami and check that scylla installed correctly

2021-02-23 12:33 UTC, bentsi approved these changes

2021-02-23 12:34 UTC, bentsi commented
can you create AMI with this code and verify that this works?

2021-03-22 10:18 UTC, merged

2021-04-27 11:09 UTC, bentsi commented
backported to 4.4